language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
  - java -version

install:
  - curl -L -o /tmp/es-snap.zip https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.2.zip
  - unzip /tmp/es-snap.zip -d /tmp/
  - /tmp/elasticsearch-*/bin/elasticsearch -E path.repo=/tmp -E repositories.url.allowed_urls='http://*' -E node.attr.testattr=test -d
  - pip install .
  - |
    while true ; do
      curl -s http://localhost:9200/ && break
      sleep 1
    done

script:
  - python setup.py test

notifications:
  email:
    recipients:
      - fabrice.bacchella@orange.fr
