version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.6
            - image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
              environment:
                  discovery.type: single-node
        steps:
          - checkout
          - run:
              command: |
                sudo pip install .
                python setup.py test
          - store_artifacts:
              path: test-reports
              destination: test-reports
workflows:
  version: 2.1
  build_and_test:
    jobs:
        - build